AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Integradora

  Sample SAM Template for Integradora

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  # Definición de la función Lambda para obtener categorías
  GetCategoriaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_categories/
      Handler: get_categories.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        GetCategoria:
          Type: Api
          Properties:
            Path: /categoria
            Method: GET

  # Definición de la función Lambda para crear una categoría
  CreateCategoriaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create_category/
      Handler: create_category.l33ambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CreateCategoria:
          Type: Api
          Properties:
            Path: /categoria
            Method: POST

  # Definición de la función Lambda para actualizar una categoría
  UpdateCategoriaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update_category/
      Handler: update_category.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        UpdateCategoria:
          Type: Api
          Properties:
            Path: /categoria
            Method: PUT

  # Definición de la función Lambda para eliminar una categoría
  DeleteCategoriaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete_category/
      Handler: delete_category.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        DeleteCategoria:
          Type: Api
          Properties:
            Path: /categoria
            Method: DELETE

Parameters:
  DBUser:
    Type: String
    Default: 'admin'
  DBPassword:
    Type: String
    Default: 'sispe123'
  DBName:
    Type: String
    Default: 'sispedb'
  DBHost:
    Type: String
    Default: 'integradora-lambda.czc42euyq8iq.us-east-1.rds.amazonaws.com'




  # Definición de la función Lambda para obtener raitings
  GetRaitingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_raiting/
      Handler: get_raiting.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        GetRaiting:
          Type: Api
          Properties:
            Path: /raiting/{id}
            Method: GET

  # Definición de la función Lambda para crear un raiting
  CreateRaitingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create_raiting/
      Handler: create_raiting.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CreateRaiting:
          Type: Api
          Properties:
            Path: /raiting
            Method: POST

  # Definición de la función Lambda para actualizar un raiting
  UpdateRaitingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update_raiting/
      Handler: update_raiting.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        UpdateRaiting:
          Type: Api
          Properties:
            Path: /raiting/{id}
            Method: PUT

  # Definición de la función Lambda para eliminar un raiting
  DeleteRaitingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete_raiting/
      Handler: delete_raiting.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        DeleteRaiting:
          Type: Api
          Properties:
            Path: /raiting/{id}
            Method: DELETE

Parameters:
  DBUser:
    Type: String
    Default: 'admin'
  DBPassword:
    Type: String
    Default: 'nhL5zPpY1I9w'
  DBName:
    Type: String
    Default: 'sispe'
  DBHost:
    Type: String
    Default: 'integradora-lambda.czc42euyq8iq.us-east-1.rds.amazonaws.com'


  

Outputs:
  GetCategoriaApi:
    Description: "API Gateway endpoint URL for Prod stage for GetCategoria function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/categoria/"
  CreateCategoriaApi:
    Description: "API Gateway endpoint URL for Prod stage for CreateCategoria function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/categoria/"
  UpdateCategoriaApi:
    Description: "API Gateway endpoint URL for Prod stage for UpdateCategoria function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/categoria/"
  DeleteCategoriaApi:
    Description: "API Gateway endpoint URL for Prod stage for DeleteCategoria function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/categoria/"
    GetRaitingApi:
    Description: "API Gateway endpoint URL for Prod stage for GetRaiting function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/raiting/{id}"
  CreateRaitingApi:
    Description: "API Gateway endpoint URL for Prod stage for CreateRaiting function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/raiting"
  UpdateRaitingApi:
    Description: "API Gateway endpoint URL for Prod stage for UpdateRaiting function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/raiting/{id}"
  DeleteRaitingApi:
    Description: "API Gateway endpoint URL for Prod stage for DeleteRaiting function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/raiting/{id}"
