AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Integradora

  Sample SAM Template for Integradora

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  # Definición de la función Lambda para obtener categorías
  GetCategoriaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_categories/
      Handler: get_categories.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        GetCategoria:
          Type: Api
          Properties:
            Path: /categoria
            Method: GET

  # Definición de la función Lambda para crear una categoría
  CreateCategoriaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create_category/
      Handler: create_category.l33ambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CreateCategoria:
          Type: Api
          Properties:
            Path: /categoria
            Method: POST

  # Definición de la función Lambda para actualizar una categoría
  UpdateCategoriaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update_category/
      Handler: update_category.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        UpdateCategoria:
          Type: Api
          Properties:
            Path: /categoria
            Method: PUT

  # Definición de la función Lambda para eliminar una categoría
  DeleteCategoriaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete_category/
      Handler: delete_category.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        DeleteCategoria:
          Type: Api
          Properties:
            Path: /categoria
            Method: DELETE

  CreateFavoriteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create_favorite/
      Handler: create_favorite.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CreateFavorito:
          Type: Api
          Properties:
            Path: /favorito
            Method: POST

  DeleteFavoriteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete_favorite/
      Handler: delete_favorite.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        DeleteFavorito:
          Type: Api
          Properties:
            Path: /favorito
            Method: DELETE

  GetFavoritesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_favorites/
      Handler: get_favorites.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        GetFavorito:
          Type: Api
          Properties:
            Path: /favorito
            Method: GET

Parameters:
  DBUser:
    Type: String
    Default: 'admin'
  DBPassword:
    Type: String
    Default: 'sispe123'
  DBName:
    Type: String
    Default: 'sispedb'
  DBHost:
    Type: String
    Default: 'integradora-lambda.czc42euyq8iq.us-east-1.rds.amazonaws.com'

Outputs:
  GetCategoriaApi:
    Description: "API Gateway endpoint URL for Prod stage for GetCategoria function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/categoria/"
  CreateCategoriaApi:
    Description: "API Gateway endpoint URL for Prod stage for CreateCategoria function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/categoria/"
  UpdateCategoriaApi:
    Description: "API Gateway endpoint URL for Prod stage for UpdateCategoria function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/categoria/"
  DeleteCategoriaApi:
    Description: "API Gateway endpoint URL for Prod stage for DeleteCategoria function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/categoria/"
  CreateFavoriteApi:
    Description: "API Gateway endpoint URL for Prod stage for CreateFavorite function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/favorito"
  DeleteFavoriteApi:
    Description: "API Gateway endpoint URL for Prod stage for DeleteFavorite function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/favorito"
  GetFavoriteApi:
    Description: "API Gateway endpoint URL for Prod stage for GetFavorite function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/favorito"