AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Integradora

  Sample SAM Template for Integradora

Globals:
  Function:
    Timeout: 100
    MemorySize: 128

Resources:
  # Definición de la función Lambda para obtener categorías
  GetCategoriaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_categories/
      Handler: get_categories.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        GetCategoria:
          Type: Api
          Properties:
            Path: /categoria
            Method: GET

  # Definición de la función Lambda para crear una categoría
  CreateCategoriaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create_category/
      Handler: create_category.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CreateCategoria:
          Type: Api
          Properties:
            Path: /categoria
            Method: POST

  # Definición de la función Lambda para actualizar una categoría
  UpdateCategoriaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update_category/
      Handler: update_category.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        UpdateCategoria:
          Type: Api
          Properties:
            Path: /categoria
            Method: PUT

  # Definición de la función Lambda para eliminar una categoría
  DeleteCategoriaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete_category/
      Handler: delete_category.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        DeleteCategoria:
          Type: Api
          Properties:
            Path: /categoria
            Method: DELETE

  # Definición de la función Lambda para crear una subscripción
  CreateSubscriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create_subscription/
      Handler: create_subscription.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
          DB_NAME: !Ref DBName
          DB_HOST: !Ref DBHost
      Events:
        CreateSubscription:
          Type: Api
          Properties:
            Path: /subscription
            Method: POST

  # Definición de la función Lambda para obtener una subcripción
  GetSubscriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_subscription/
      Handler: get_subscription.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
          DB_NAME: !Ref DBName
          DB_HOST: !Ref DBHost
      Events:
        GetSubscription:
          Type: Api
          Properties:
            Path: /subscription/{subscription_id}
            Method: GET

Parameters:
  DBUser:
    Type: String
    Default: 'admin'
  DBPassword:
    Type: String
    Default: 'nhL5zPpY1I9w'
  DBName:
    Type: String
    Default: 'sispe'
  DBHost:
    Type: String
    Default: 'integradora-lambda.czc42euyq8iq.us-east-1.rds.amazonaws.com'

Outputs:
  GetCategoriaApi:
    Description: "API Gateway endpoint URL for Prod stage for GetCategoria function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/categoria/"
  CreateCategoriaApi:
    Description: "API Gateway endpoint URL for Prod stage for CreateCategoria function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/categoria/"
  UpdateCategoriaApi:
    Description: "API Gateway endpoint URL for Prod stage for UpdateCategoria function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/categoria/"
  DeleteCategoriaApi:
    Description: "API Gateway endpoint URL for Prod stage for DeleteCategoria function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/categoria/"
  CreateSubscriptionApi:
    Description: "API Gateway endpoint URL for Prod stage for CreateSubscription function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/subscription/"
  GetSubscriptionApi:
    Description: "API Gateway endpoint URL for Prod stage for GetSubscription function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/subscription/"
